name: Auto Unzip

on:
  push:
    paths:
      - "*.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip file
        run: |
          unzip -o source.zip -d extracted

      - name: Commit hasil unzip
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto unzip source.zip"
          git push
